apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /nfs
