apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /cephfs/mongodb_data
