apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: docker
        image: docker:dind
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run
        securityContext:
          privileged: true
      - name: jenkins
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: {{ .Release.Name }}
        volumeMounts:
        {{- if .Values.persistent.enabled }}
        - name: {{ .Release.Name }}
          mountPath: /var/jenkins_home
        {{- end }}
        - name: nginx
          mountPath: /var/www_data
        - name: docker-sock
          mountPath: /var/run
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
      dnsConfig:
        nameservers:
        {{- range .Values.nameservers }}
        - {{ . }}
        {{- end }}
        searches:
        - {{ .Values.domain }}
      volumes:
      {{- if .Values.persistent.enabled }}
      - name: {{ .Release.Name }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      {{- end }}
      - name: nginx
        persistentVolumeClaim:
          claimName: nginx
      - name: docker-sock
        emptyDir: {}

# password: j3nK1n$@dm1n
