apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: ghym
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
  externalIPs:
  - 172.16.0.8
