apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/cephfs/kafka_data/data"
