persistent:
  enabled: true
  storage: 5Gi
  path: /cifs/prometheus_data
externalIP:
- 172.16.0.15
service:
  type: ClusterIP
  port:
    ui: 9090
    alertmanager: 9093
replicaCount: 1
image:
  repository: maxkadyshev/prometheus
  tag: v2.48.4
domain: ghym.local
ingress:
  enabled: true
  className: nginx
  tls:
    enabled: true
resources:
  limits:
    memory: 512M
  requests:
    memory: 256M

# helm upgrade -i -n ghym --atomic --wait --debug prometheus . -f values.yaml
