apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: ghym
spec:
  selector:
    app: gitlab
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
  - name: ssh
    protocol: TCP
    port: 22
