apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: ghym
  labels:
    app: zookeeper
spec:
  ports:
  - name: zookeeper
    port: 2181
    protocol: TCP
  selector:
    app: zookeeper
  externalIPs:
  - 172.16.0.8
