global:
  resolve_timeout:  5m
route:
  group_by: ['alertname']
  group_interval: 30s
  repeat_interval: 30s
  receiver: telegram
receivers:
- name: telegram
  telegram_configs:
  - bot_token: '6525866663:AAHc6p9N0U5pgkSBtUPjXq_BSEXP0oQ96wk'
    api_url: 'https://api.telegram.org'
    chat_id: -1002075974086
    parse_mode: ''
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
