apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghym
  namespace: ghym
spec:
  ingressClassName: nginx
  rules:
  - host: ghym.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
  - host: kadyshev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
  - host: '*.a.ghym.local'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache
            port:
              number: 80
  - host: '*.ghym.local'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
  tls:
  - hosts:
    - kadyshev.local
    - ghym.local
    - '*.a.ghym.local'
    - '*.ghym.local'
    secretName: ghym.local
