apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghym
  namespace: ghym
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.ghym.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: grafana
              port:
                number: 3000
  - host: mysql.ghym.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jenkins
              port:
                number: 80
  - host: jenkins.ghym.ae
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jenkins
              port:
                number: 8080
  - host: ghym.ae
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80
  - host: kadyshev.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80
  - host: "*.a.ghym.ae"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache
            port:
              number: 80
  - host: "*.ghym.ae"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
