apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /cephfs/kafka_data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /cephfs/zookeeper_data
