version: '3.7'
services:
 registry:
  container_name: 'registry'
  image: 'registry:2'
  restart: 'always'
  ports:
  - '5000:5000'
  volumes:
  - '/docker_registry/:/var/lib/registry/'
  - '/docker_registry/cert/:/etc/docker/certs.d/'
  - '/docker_registry/config.yaml:/etc/docker/registry/config.yml'
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: '/etc/docker/certs.d/ghym_docker.crt'
    REGISTRY_HTTP_TLS_KEY: '/etc/docker/certs.d/ghym_docker.key'
