apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: ghym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: maxkadyshev/jenkins:2.387.2-lts-jdk11-1
        ports:
        - containerPort: 8080
          name: jenkins
        volumeMounts:
        - name: jenkins
          mountPath: /var/jenkins_home
        - name: nginx
          mountPath: /var/www_data
      dnsConfig:
        nameservers:
        - 172.16.0.8
        searches:
        - ghym.local
      volumes:
      - name: jenkins
        persistentVolumeClaim:
          claimName: jenkins
      - name: nginx
        persistentVolumeClaim:
          claimName: nginx
# password: j3nK1n$@dm1n
