apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: ghym
spec:
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: maxkadyshev/sandbox:14.6
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: password
        - name: PGDATA
          value: /data/pgdata
        volumeMounts:
        - name: postgresql
          mountPath: /data
      dnsConfig:
        nameservers:
        - 172.16.0.8
        searches:
        - ghym.local
      volumes:
      - name: postgresql
        persistentVolumeClaim:
          claimName: postgresql
