apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: ghym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:3.8
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
#        - name: ZOO_ENABLE_AUTH
#          value: "yes"
#        - name: ZOO_SERVER_USERS
#          value: "user"
#        - name: ZOO_SERVER_PASSWORDS
#          value: "bitnami"
        volumeMounts:
          - name: zookeeper
            mountPath: /bitnami
      volumes:
      - name: zookeeper
        persistentVolumeClaim:
          claimName: zookeeper
