backup:
  storage: 1Gi
  path: /cifs/backup/grafana/
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  className: nginx
  tls:
    enables: true
domain: ghym.local
nameservers:
- 8.8.8.8
- 8.8.4.4
replicaCount: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /robots.txt
    port: 3000
    scheme: HTTP
image:
  repository: maxkadyshev/grafana
  tag: 10.2.3-ubuntu
resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 1000Mi

# UI Password: 9r@f@n@

# helm upgrade -i -n ghym --atomic --wait --debug grafana . -f values.yaml
