apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
      - name: init-{{ .Release.Name }}
        image: busybox:1.28
        command: [ "/bin/sh", "-c", "cp -R /backup/* /grafana/" ]
        volumeMounts:
        - name: {{ .Release.Name }}
          mountPath: /grafana
        - name: {{ .Release.Name }}-backup
          mountPath: /backup
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: GF_INSTALL_PLUGINS
          value: "grafana-clock-panel,grafana-simple-json-datasource"
        readinessProbe:
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port }}
            scheme: {{ .Values.readinessProbe.httpGet.scheme }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "printf '#!/bin/sh\ncp -Rf /grafana/* /backup/ 2>&1\n' > /etc/cron.daily/backup"]
        volumeMounts:
        - name: {{ .Release.Name }}-backup
          mountPath: /backup
        - name: {{ .Release.Name }}
          mountPath: /var/lib/grafana
      dnsConfig:
        nameservers:
        {{- range .Values.nameservers }}
        - {{ . }}
        {{- end }}
        searches:
        - {{ .Values.domain }}
      volumes:
      - name: {{ .Release.Name }}-backup
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      - name: {{ .Release.Name }}
        emptyDir: {}
