apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: {{ .Values.backup.storage }}
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: {{ .Values.backup.path }}
