persistent:
  enabled: true
  storage: 1Gi
  path: /cifs/jenkins_data
service:
  type: ClusterIP
  port: 8008
  targetPort: 8080
replicaCount: 1
image:
  repository: maxkadyshev/jenkins
  pullPolicy: IfNotPresent
  tag: 2.426.2-lts-jdk21-8
nameservers:
- 8.8.8.8
- 8.8.4.4
domain: ghym.local
ingress:
  enabled: true
  className: nginx
  tls:
    enables: true
resources:
  limits:
    memory: 1.5G
  requests:
    memory: 1G

# helm upgrade -i -n ghym --atomic --wait --debug jenkins . -f values.yaml
