apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ required "A valid .Values.password entry required" .Values.password | b64enc }}
