apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: client
    port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: mysql
  externalIPs:
  {{- range .Values.externalIP }}
  - {{ . }}
  {{- end }}
