apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: ghym
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
