apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ghym
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "printf '#!/bin/bash\nmysqldump --all-databases > /nfs/mysql_all_databases.sql 2>&1\n' > /etc/cron.daily/backup"]
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        - name: backup
          mountPath: /backup
      dnsConfig:
        nameservers:
        - 172.16.0.8
        searches:
        - ghym.local
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql
      - name: backup
        persistentVolumeClaim:
          claimName: backup
