apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ghym
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
