apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /cephfs/redis_data/master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-replica
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /cephfs/redis_data/replica
