apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: ghym
  labels:
    app: apache
    type: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
      type: front-end
  template:
    metadata:
      labels:
        app: apache
        type: front-end
    spec:
      containers:
      - name: apache
        image: httpd:2.4.54
        volumeMounts:
        - name: apache
          mountPath: /usr/local/apache2/conf
      dnsConfig:
        nameservers:
        - 172.16.0.8
        searches:
        - ghym.local
      volumes:
      - name: apache
        persistentVolumeClaim:
          claimName: apache
