apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-conf
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  local:
    path: /cephfs/cassandra_data/conf
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodetype
          operator: In
          values:
          - wn
