apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  local:
    path: /cephfs/cassandra_data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodetype
          operator: In
          values:
          - wn
