apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-conf
  namespace: ghym
spec:
   accessModes:
     - ReadWriteOnce
   storageClassName: local-storage
   resources:
       requests:
           storage: 1Gi
