apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ghym
spec:
  ports:
  - name: jenkins
    port: 8008
    targetPort: 8080
    protocol: TCP
  selector:
    app: jenkins
  externalIPs:
  - 172.16.0.8
