apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: ghym
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka
    protocol: TCP
  selector:
    app: kafka
    id: "0"
  externalIPs:
  - 172.16.0.7
