apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: ghym
  labels:
    app: postgresql
    name: postgresql
spec:
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:12.11
        volumeMounts:
        - name: postgresql
          mountPath: /data
        env:
          - name: POSTGRES_PASSWORD
            value: p05t9rE59I6hYm
          - name: PGDATA
            value: /data/pgdata
      dnsConfig:
        nameservers:
        - 172.16.0.8
        searches:
        - ghym.local
      volumes:
      - name: postgresql
        persistentVolumeClaim:
          claimName: postgresql
