apiVersion: v1
kind: Namespace
metadata:
  name: ghym
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ghym
  namespace: ghym
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ghym
  namespace: ghym
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list","watch"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get","list","watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list","watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ghym
  namespace: ghym
roleRef:
  kind: Role
  name: ghym
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: ghym
  namespace: ghym
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ghym
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get","list","watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ghym
roleRef:
  kind: ClusterRole
  name: ghym
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: ghym
  namespace: ghym
  apiGroup: rbac.authorization.k8s.io
