apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/cephfs/zookeeper_data"
