apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-conf-root
  namespace: ghym
data:
  named.conf: |
    include "/etc/bind/named.conf.logging";
    include "/etc/bind/named.conf.options";
    include "/etc/bind/custom/conf/0.16.172.in-addr.arpa.conf";
    include "/etc/bind/custom/conf/ghym.local.conf";
  named.conf.logging: |
    logging {
      category default { default_stderr; };
      category queries { default_stderr; };
    };
  named.conf.options: |
    options {
      directory "/var/cache/bind";
      dnssec-validation no;
      auth-nxdomain no;    # conform to RFC1035
      listen-on-v6 { any; };
      max-cache-size 90%;
      response-policy { zone "ghym.local"; };
      forwarders {
        94.200.200.200;
        91.74.74.74;
      };
      recursion yes;
      allow-recursion {
        any;
      };
      allow-query {
        any;
      };
    };
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-conf-custom
  namespace: ghym
data:
  0.16.172.in-addr.arpa.conf: |
    zone "0.16.172.in-addr.arpa" {
      type master;
      allow-transfer { any; };
      allow-update { any; };
      file "/etc/bind/custom/zone/0.16.172.in-addr.arpa";
    };
  ghym.local.conf: |
    zone "ghym.local" IN {
      type master;
      allow-transfer { any; };
      allow-update { any; };
      file "/etc/bind/custom/zone/ghym.local";
    };
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-conf-zone
  namespace: ghym
data:
  0.16.172.in-addr.arpa: |
    $TTL 3600
    @                               IN   SOA     bind. admin.bind. (
                                                 1672835141     ; Serial number
                                                 1200           ; Refresh time
                                                 180            ; Retry time
                                                 1209600        ; Expiry time
                                                 10800          ; Negative Cache TTL
    )
    0.16.172.in-addr.arpa.          IN   NS      bind.          ; PTR
  ghym.local: |
    $TTL 3600
    @                               IN   SOA     bind.  admin.bind. (
                                                 1672835142     ; Serial number
                                                 1200           ; Refresh time
                                                 180            ; Retry time
                                                 1209600        ; Expiry time
                                                 10800          ; Negative Cache TTL
    )
                                    IN   NS      bind.          ; A
