apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 25Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /cephfs/postgresql_data
