apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: apache
    type: front-end
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apache
      type: front-end
  template:
    metadata:
      labels:
        app: apache
        type: front-end
    spec:
      containers:
      - name: apache
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        volumeMounts:
        - name: {{ .Release.Name }}-conf
          mountPath: /usr/local/apache2/conf
          readOnly: true
        - name: {{ .Release.Name }}-extra
          mountPath: /usr/local/apache2/conf/extra
          readOnly: true
        {{ if .Values.persistent.enabled }}
        - name: {{ .Release.Name }}-data
          mountPath: /usr/local/apache2/conf/www
        {{ end }}
      volumes:
      {{- if .Values.persistent.enabled }}
      - name: {{ .Release.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      {{- end }}
      - name: {{ .Release.Name }}-conf
        configMap:
          name: {{ .Release.Name }}-conf
      - name: {{ .Release.Name }}-extra
        configMap:
          name: {{ .Release.Name }}-extra
