---
- name: Preparation for creating Kubernetes cluster
  hosts: k8s
  become: yes
  pre_tasks:
   - apt:
      name: docker.io
      state: present
   - name: Start the Docker service
     systemd:
       name: docker
       enabled: yes
       state: started
   - name: Add Kubernetes Signing Key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present
   - name: Add specified repository into sources list using specified filename
     apt_repository:
       repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
       state: present
   - name: Install kubeadm
     apt:
      name: kubeadm
      state: present
   - name: Install kubelet
     apt:
      name: kubelet
      state: present
   - name: Install kubectl
     apt:
      name: kubectl
      state: present
   - name: Remove swapfile from /etc/fstab
     mount:
       name: "{{ item }}"
       fstype: swap
       state: absent
     with_items:
       - swap
       - none
   - name: Disable swap
     command: swapoff -a
     when: ansible_swaptotal_mb > 0
#   - name: Initialize the Kubernetes cluster using kubeadm
#      command: kubeadm init --apiserver-advertise-address="172.16.0.1" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
#- name: Setup kubeconfig for vagrant user
#    command: "{{ item }}"
#    with_items:
#     - mkdir -p /home/vagrant/.kube
#     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
#     - chown vagrant:vagrant /home/vagrant/.kube/config
#- name: Install calico pod network
#    become: false
#    command: kubectl create -f https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
#- name: Generate join command
#    command: kubeadm token create --print-join-command
#    register: join_command
#  - name: Copy join command to local file
#    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
#- name: Copy the join command to server location
#    copy: src=join-command dest=/tmp/join-command.sh mode=0777
#  - name: Join the node to cluster
#    command: sh /tmp/join-command.sh
