---
- name: Preinstalled software on all YUM hosts
  hosts: HyperV
  become: yes
  pre_tasks:
   - name: Install screen
     yum:
       name: screen
       state: installed
   -  name: Install mc
      yum:
       name: mc
       state: installed
   - name: Install docker
     yum:
       name: docker
       state: installed
   - name: Install ceph-common
     yum:
       name: ceph-common
       state: installed
   - name: Set timezone to Asia/Dubai
     timezone:
       name: Asia/Dubai
#   - name: Install Load Balancer
#     yum:
#       name: ipvsadm
#       state: installed
#   - name: Enable IP forwarding
#     sysctl:
#       name: net.ipv4.ip_forward
#       value: "1"
#       state: present
#   - name: Start the ipvsadm service
#     systemd:
#       state: started
#       name: ipvsadm
- name: Preinstalled software on all APT hosts
  hosts: Ubuntu
  become: yes
  pre_tasks:
   - name: Update all packages to their latest version
     apt:
       name: "*"
       state: latest
   - name: Install screen
     apt:
       name: screen
       update_cache: yes
       state: present
   - name: Install mc
     apt:
       name: mc
       state: present
   - name: Install net-tools
     apt:
       name: net-tools
       state: present
   - name: Install ceph-common
     apt:
       name: ceph-common
       state: present
   - name: Install mlocate
     apt:
       name: mlocate
       state: present
   - name: Set timezone to Asia/Dubai
     timezone:
       name: Asia/Dubai
- name: K8S preconfiguration
  hosts: k8s
  become: yes
  pre_tasks:
   - name: Install docker
     apt:
       name: docker.io
       state: present
   - name: Enable service docker
     systemd:
       name: docker
       enabled: yes
   - name: Make sure a service unit is running
     systemd:
       name: docker
       state: started
   - name: Add kubernetes sighned key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present
   - name: Add kubernetes repositories
     apt_repository:
       repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
       state: present
   - name: Install kubeadm
     apt:
       name: kubeadm
       state: present
   - name: Install kubelet
     apt:
       name: kubelet
       state: present
   - name: Install kubectl
     apt:
       name: kubectl
       state: present
   - name: Copy system hosts file
     copy:
       src: '/home/max/github.com/ghym/Ansible/hosts'
       dest: '/etc/hosts'
