dbUser:
  password: 'c@ssan6ra'
podSecurityContext:
  enabled: false
containerSecurityContext:
  runAsUser: 0
  runAsNonRoot: false
resources:
  limits:
    cpu: 2
    memory: 4G
  requests:
    cpu: 200m
    memory: 2G
jvm:
  extraOpts: '-Dcom.sun.managment.jmxremote.authenticate=false'
  maxHeapSize: 500M
  newHeapSize: 200M
extraDeploy:
- |
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: cassandra
      labels:
        type: local
        app.kubernetes.io/managed-by: Helm
      annotations:
        meta.helm.sh/release-namespace: ghym
        meta.helm.sh/release-name: cassandra
    spec:
      storageClassName: local-storage
      capacity:
        storage: 8Gi
      accessModes:
      - ReadWriteOnce
      hostPath:
        path: /cephfs/cassandra_data
livenessProbe:
  initialDelaySeconds: 300
persistence:
  storageClass: local-storage

# helm -n ghym upgrade -i --atomic --debug --wait --timeout 20m0s cassandra bitnami/cassandra -f Helm/cassandra.yaml
