apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
    - /prometheus/ghym-rule.yml
    scrape_configs:
    - job_name: "prometheus"
      static_configs:
      - targets:
        - 0.0.0.0:{{ .Values.service.port }}
    - job_name: "node-exporter"
      static_configs:
      - targets:
        - 172.16.0.15:9100
        - 172.16.0.16:9100
        - 172.16.0.17:9100
    - job_name: "kube-state-metrics"
      static_configs:
      - targets:
        - 172.16.0.15:8080
  ghym-rule.yml: |
    groups:
    - name: graph
      rules:
      - record: node_memory_MemFree_percent
        expr: 100 - 100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes
    - name: alert
      rules:
      - alert: off-line
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{{ "{{" }} $labels.instance {{ "}}" }} off-line"
          description: "Node {{ "{{" }} $labels.instance {{ "}}" }} of job {{ "{{" }} $labels.job {{ "}}" }} has been down for more than 1 minute"
      - alert: pod-down
        expr: kube_pod_status_ready{condition="true"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{{ "{{" }} $labels.pod {{ "}}" }} off-line"
          description: "Pod {{ "{{" }} $labels.pod {{ "}}" }} at namespace {{ "{{" }} $labels.namespace {{ "}}" }} on the node {{ "{{" }} $labels.instance {{ "}}" }} is down for more than 1 minute"
