apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port.ui }}
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/sh", "-c", "start-stop-daemon -Sbx /usr/bin/alertmanager -- --config.file=/usr/bin/alertmanager.yml && start-stop-daemon -Sbx /usr/bin/blackbox -- --config.file=/usr/bin/blackbox.yml" ]
        volumeMounts:
        - name: {{ .Release.Name }}-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: {{ .Release.Name }}-config
          mountPath: /prometheus/ghym-rule.yml
          subPath: ghym-rule.yml
        {{- if .Values.persistent.enabled }}
        - name: {{ .Release.Name }}
          mountPath: /metrics
        {{- end }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
      volumes:
      - name: {{ .Release.Name }}-config
        configMap:
          name: {{ .Release.Name }}
      {{- if .Values.persistent.enabled }}
      - name: {{ .Release.Name }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      {{- end }}
