apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
  externalIPs:
  {{- range .Values.externalIP }}
  - {{ . }}
  {{ end }}
