apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-conf-root
  namespace: {{ .Release.Namespace }}
data:
  fastcgi_params: |
    fastcgi_param  QUERY_STRING       $query_string;
    fastcgi_param  REQUEST_METHOD     $request_method;
    fastcgi_param  CONTENT_TYPE       $content_type;
    fastcgi_param  CONTENT_LENGTH     $content_length;
    fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
    fastcgi_param  REQUEST_URI        $request_uri;
    fastcgi_param  DOCUMENT_URI       $document_uri;
    fastcgi_param  DOCUMENT_ROOT      $document_root;
    fastcgi_param  SERVER_PROTOCOL    $server_protocol;
    fastcgi_param  REQUEST_SCHEME     $scheme;
    fastcgi_param  HTTPS              $https if_not_empty;
    fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
    fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;
    fastcgi_param  REMOTE_ADDR        $remote_addr;
    fastcgi_param  REMOTE_PORT        $remote_port;
    fastcgi_param  SERVER_ADDR        $server_addr;
    fastcgi_param  SERVER_PORT        $server_port;
    fastcgi_param  SERVER_NAME        $server_name;
    fastcgi_param  REDIRECT_STATUS    200;
  mime.types: |
    types {
        text/html                                                                 html htm shtml;
        text/css                                                                  css;
        text/xml                                                                  xml;
        image/gif                                                                 gif;
        image/jpeg                                                                jpeg jpg;
        application/javascript                                                    js;
        application/atom+xml                                                      atom;
        application/rss+xml                                                       rss;
        text/mathml                                                               mml;
        text/plain                                                                txt;
        text/vnd.sun.j2me.app-descriptor                                          jad;
        text/vnd.wap.wml                                                          wml;
        text/x-component                                                          htc;
        image/avif                                                                avif;
        image/png                                                                 png;
        image/svg+xml                                                             svg svgz;
        image/tiff                                                                tif tiff;
        image/vnd.wap.wbmp                                                        wbmp;
        image/webp                                                                webp;
        image/x-icon                                                              ico;
        image/x-jng                                                               jng;
        image/x-ms-bmp                                                            bmp;
        font/woff                                                                 woff;
        font/woff2                                                                woff2;
        application/java-archive                                                  jar war ear;
        application/json                                                          json;
        application/mac-binhex40                                                  hqx;
        application/msword                                                        doc;
        application/pdf                                                           pdf;
        application/postscript                                                    ps eps ai;
        application/rtf                                                           rtf;
        application/vnd.apple.mpegurl                                             m3u8;
        application/vnd.google-earth.kml+xml                                      kml;
        application/vnd.google-earth.kmz                                          kmz;
        application/vnd.ms-excel                                                  xls;
        application/vnd.ms-fontobject                                             eot;
        application/vnd.ms-powerpoint                                             ppt;
        application/vnd.oasis.opendocument.graphics                               odg;
        application/vnd.oasis.opendocument.presentation                           odp;
        application/vnd.oasis.opendocument.spreadsheet                            ods;
        application/vnd.oasis.opendocument.text                                   odt;
        application/vnd.openxmlformats-officedocument.presentationml.presentation pptx;
        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet         xlsx;
        application/vnd.openxmlformats-officedocument.wordprocessingml.document   docx;
        application/vnd.wap.wmlc                                                  wmlc;
        application/wasm                                                          wasm;
        application/x-7z-compressed                                               7z;
        application/x-cocoa                                                       cco;
        application/x-java-archive-diff                                           jardiff;
        application/x-java-jnlp-file                                              jnlp;
        application/x-makeself                                                    run;
        application/x-perl                                                        pl pm;
        application/x-pilot                                                       prc pdb;
        application/x-rar-compressed                                              rar;
        application/x-redhat-package-manager                                      rpm;
        application/x-sea                                                         sea;
        application/x-shockwave-flash                                             swf;
        application/x-stuffit                                                     sit;
        application/x-tcl                                                         tcl tk;
        application/x-x509-ca-cert                                                der pem crt;
        application/x-xpinstall                                                   xpi;
        application/xhtml+xml                                                     xhtml;
        application/xspf+xml                                                      xspf;
        application/zip                                                           zip;
        application/octet-stream                                                  bin exe dll;
        application/octet-stream                                                  deb;
        application/octet-stream                                                  dmg;
        application/octet-stream                                                  iso img;
        application/octet-stream                                                  msi msp msm;
        audio/midi                                                                mid midi kar;
        audio/mpeg                                                                mp3;
        audio/ogg                                                                 ogg;
        audio/x-m4a                                                               m4a;
        audio/x-realaudio                                                         ra;
        video/3gpp                                                                3gpp 3gp;
        video/mp2t                                                                ts;
        video/mp4                                                                 mp4;
        video/mpeg                                                                mpeg mpg;
        video/quicktime                                                           mov;
        video/webm                                                                webm;
        video/x-flv                                                               flv;
        video/x-m4v                                                               m4v;
        video/x-mng                                                               mng;
        video/x-ms-asf                                                            asx asf;
        video/x-ms-wmv                                                            wmv;
        video/x-msvideo                                                           avi;
    }
  nginx.conf: |
    user             nginx;
    worker_processes auto;
    error_log        /var/log/nginx/error.log error;
    pid              /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include           /etc/nginx/mime.types;
        default_type      application/octet-stream;
        log_format        main '$remote_addr - $remote_user [$time_local] "$request" '
                               '$status $body_bytes_sent "$http_referer" '
                               '"$http_user_agent" "$http_x_forwarded_for"';
        access_log        /var/log/nginx/access.log  main;
        sendfile          on;
        keepalive_timeout 65;
        gzip              on;
        include           /etc/nginx/conf.d/*.conf;
    }
  scgi_params: |
    scgi_param  REQUEST_METHOD     $request_method;
    scgi_param  REQUEST_URI        $request_uri;
    scgi_param  QUERY_STRING       $query_string;
    scgi_param  CONTENT_TYPE       $content_type;
    scgi_param  DOCUMENT_URI       $document_uri;
    scgi_param  DOCUMENT_ROOT      $document_root;
    scgi_param  SCGI               1;
    scgi_param  SERVER_PROTOCOL    $server_protocol;
    scgi_param  REQUEST_SCHEME     $scheme;
    scgi_param  HTTPS              $https if_not_empty;
    scgi_param  REMOTE_ADDR        $remote_addr;
    scgi_param  REMOTE_PORT        $remote_port;
    scgi_param  SERVER_PORT        $server_port;
    scgi_param  SERVER_NAME        $server_name;
  uwsgi_params: |
    uwsgi_param  QUERY_STRING       $query_string;
    uwsgi_param  REQUEST_METHOD     $request_method;
    uwsgi_param  CONTENT_TYPE       $content_type;
    uwsgi_param  CONTENT_LENGTH     $content_length;
    uwsgi_param  REQUEST_URI        $request_uri;
    uwsgi_param  PATH_INFO          $document_uri;
    uwsgi_param  DOCUMENT_ROOT      $document_root;
    uwsgi_param  SERVER_PROTOCOL    $server_protocol;
    uwsgi_param  REQUEST_SCHEME     $scheme;
    uwsgi_param  HTTPS              $https if_not_empty;
    uwsgi_param  REMOTE_ADDR        $remote_addr;
    uwsgi_param  REMOTE_PORT        $remote_port;
    uwsgi_param  SERVER_PORT        $server_port;
    uwsgi_param  SERVER_NAME        $server_name;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-conf-d
  namespace: {{ .Release.Namespace }}
data:
  kadyshev.local.conf: |
    server {
     listen               80;
     server_name          kadyshev.local;
     location / {
      root   /etc/nginx/www/kadyshev.com;
      index  index.html;
    }
     error_page   500 502 503 504  /50x.html;
     location = /50x.html {
      root   /usr/share/nginx/html;
     }
    }
  ghym.local.conf: |
    server {
     listen               80;
     server_name          ghym.local;
     location / {
      root   /etc/nginx/www/ghym.ae/script;
      index  index.php;
     }
     location ~ \.php$ {
        include        fastcgi_params;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        root           /etc/nginx/www/ghym.ae/script;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
     }
     location ~ /\.ht {
        deny  all;
     }
    }
# ghym
