apiVersion: v1
kind: LimitRange
metadata:
  name: ghym
  namespace: ghym
spec:
  limits:
  - type: Container
    default:
      cpu: 0.1
      memory: 100M
      ephemeral-storage: 1Gi
    defaultRequest:
      cpu: 0.1
      memory: 100M
      ephemeral-storage: 1Gi
    max:
      cpu: 2
      memory: 4G
      ephemeral-storage: 25G
  - type: PersistentVolumeClaim
    max:
      storage: 25G
