apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: gitlab
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        volumeMounts:
        - name: {{ .Release.Name }}-conf
          mountPath: /etc/gitlab
        {{- if .Values.persistent.enabled }}
        - name: {{ .Release.Name }}-data
          mountPath: /var/opt/gitlab
        {{- end }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
      dnsConfig:
        nameservers:
        {{- range .Values.nameservers }}
        - {{ . }}
        {{- end }}
        searches:
        - {{ .Values.domain }}
      volumes:
      {{- if .Values.persistent.enabled }}
      - name: {{ .Release.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      {{- end }}
      - name: {{ .Release.Name }}-conf
        configMap:
          name: {{ .Release.Name }}
