apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gitlab
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
  {{- if .Values.service.ssl.enabled }}
  - name: https
    protocol: TCP
    port: {{ .Values.service.ssl.port }}
  {{- end }}
  {{- if .Values.service.ssh.enabled }}
  - name: ssh
    protocol: TCP
    port: {{ .Values.service.ssh.port }}
  {{ end }}
