apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ghym
  labels:
    name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongodb
  externalIPs:
  - 172.16.0.8
