apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: ghym
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi
